# Generated by Django 3.0.5 on 2020-04-27 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='guest',
            field=models.ManyToManyField(blank=True, related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
