# Generated by Django 3.0.7 on 2020-12-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200504_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stopword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopword', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['-date_created']},
        ),
    ]
